//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IwsHttpBinding")]
    public interface IwsHttpBinding {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsHttpBinding/GetData", ReplyAction="http://tempuri.org/IwsHttpBinding/GetDataResponse")]
        System.Data.DataTable GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsHttpBinding/GetData", ReplyAction="http://tempuri.org/IwsHttpBinding/GetDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsHttpBinding/CreateData", ReplyAction="http://tempuri.org/IwsHttpBinding/CreateDataResponse")]
        void CreateData(AirlineBO.AirBO air);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsHttpBinding/CreateData", ReplyAction="http://tempuri.org/IwsHttpBinding/CreateDataResponse")]
        System.Threading.Tasks.Task CreateDataAsync(AirlineBO.AirBO air);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsHttpBinding/UpdateData", ReplyAction="http://tempuri.org/IwsHttpBinding/UpdateDataResponse")]
        void UpdateData(AirlineBO.AirBO air);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsHttpBinding/UpdateData", ReplyAction="http://tempuri.org/IwsHttpBinding/UpdateDataResponse")]
        System.Threading.Tasks.Task UpdateDataAsync(AirlineBO.AirBO air);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsHttpBinding/DeleteData", ReplyAction="http://tempuri.org/IwsHttpBinding/DeleteDataResponse")]
        void DeleteData(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsHttpBinding/DeleteData", ReplyAction="http://tempuri.org/IwsHttpBinding/DeleteDataResponse")]
        System.Threading.Tasks.Task DeleteDataAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsHttpBinding/GetClass", ReplyAction="http://tempuri.org/IwsHttpBinding/GetClassResponse")]
        System.Data.DataTable GetClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsHttpBinding/GetClass", ReplyAction="http://tempuri.org/IwsHttpBinding/GetClassResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetClassAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsHttpBindingChannel : AirlineApp.ServiceReference1.IwsHttpBinding, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsHttpBindingClient : System.ServiceModel.ClientBase<AirlineApp.ServiceReference1.IwsHttpBinding>, AirlineApp.ServiceReference1.IwsHttpBinding {
        
        public IwsHttpBindingClient() {
        }
        
        public IwsHttpBindingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsHttpBindingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsHttpBindingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsHttpBindingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public void CreateData(AirlineBO.AirBO air) {
            base.Channel.CreateData(air);
        }
        
        public System.Threading.Tasks.Task CreateDataAsync(AirlineBO.AirBO air) {
            return base.Channel.CreateDataAsync(air);
        }
        
        public void UpdateData(AirlineBO.AirBO air) {
            base.Channel.UpdateData(air);
        }
        
        public System.Threading.Tasks.Task UpdateDataAsync(AirlineBO.AirBO air) {
            return base.Channel.UpdateDataAsync(air);
        }
        
        public void DeleteData(int id) {
            base.Channel.DeleteData(id);
        }
        
        public System.Threading.Tasks.Task DeleteDataAsync(int id) {
            return base.Channel.DeleteDataAsync(id);
        }
        
        public System.Data.DataTable GetClass() {
            return base.Channel.GetClass();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetClassAsync() {
            return base.Channel.GetClassAsync();
        }
    }
}
