//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineApp.AirlineWS {
    using System;
    using System.Data;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AirlineWS.AirlineDetailsSoap")]
    public interface AirlineDetailsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAirlines", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllAirlines();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAirlines", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllAirlinesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AirlineDetailsSoapChannel : AirlineApp.AirlineWS.AirlineDetailsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AirlineDetailsSoapClient : System.ServiceModel.ClientBase<AirlineApp.AirlineWS.AirlineDetailsSoap>, AirlineApp.AirlineWS.AirlineDetailsSoap {
        
        public AirlineDetailsSoapClient() {
        }
        
        public AirlineDetailsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AirlineDetailsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AirlineDetailsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AirlineDetailsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetAllAirlines() {
            return base.Channel.GetAllAirlines();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllAirlinesAsync() {
            return base.Channel.GetAllAirlinesAsync();
        }

        internal void searchAirlines(string origin, string destination)
        {
            throw new NotImplementedException();
        }
    }
}
