//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineApp.AirlineWS1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AirlineWS1.AirlineDetailsSoap")]
    public interface AirlineDetailsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchAirlines", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable searchAirlines(string ori, string dest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchAirlines", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> searchAirlinesAsync(string ori, string dest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAirlines", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllAirlines();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAirlines", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllAirlinesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AirlineDetailsSoapChannel : AirlineApp.AirlineWS1.AirlineDetailsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AirlineDetailsSoapClient : System.ServiceModel.ClientBase<AirlineApp.AirlineWS1.AirlineDetailsSoap>, AirlineApp.AirlineWS1.AirlineDetailsSoap {
        
        public AirlineDetailsSoapClient() {
        }
        
        public AirlineDetailsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AirlineDetailsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AirlineDetailsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AirlineDetailsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable searchAirlines(string ori, string dest) {
            return base.Channel.searchAirlines(ori, dest);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> searchAirlinesAsync(string ori, string dest) {
            return base.Channel.searchAirlinesAsync(ori, dest);
        }
        
        public System.Data.DataTable GetAllAirlines() {
            return base.Channel.GetAllAirlines();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllAirlinesAsync() {
            return base.Channel.GetAllAirlinesAsync();
        }
    }
}
